### ISSUE TITLE
err....

### ISSUE THREAD

**Issue by sirvon** [izacus/RoboGif#5]
``` bash
RoboGif Recorder v1.1.2
Starting recording on LGH345769dc0a0...
Press Ctrl+C to stop recording.
^CRecording done, downloading file....
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
error: device offline
Could not download recording from the device.
Traceback (most recent call last):
  File "/usr/local/bin/robogif", line 9, in <module>
    load_entry_point('robogif==1.1.2', 'console_scripts', 'robogif')()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/robogif/recorder.py", line 203, in run
    os.remove(tmp_video_file)
OSError: [Errno 2] No such file or directory: '/var/folders/_d/zmg1cc01779c3fs35hcdd8sw0000gn/T/sn7JdL.mp4'
```

**Comment by izacus** [comment]
That's an `adb` error, can't do much about it from this side :/
